#!/usr/bin/env bash
# add-all-initrd-grub.sh
#
# Scans /boot for all versioned initrd.img-<version> files and generates a
# GRUB 2 menuentry block in /etc/grub.d/40_custom for each one that has a
# matching vmlinuz-<version>.  Finally runs update-grub (or grub-mkconfig)
# to make the new entries live.
#
# Environment variables (all optional):
#   BOOT_DIR      – directory to scan  (default: /boot)
#   GRUB_CUSTOM   – target file        (default: /etc/grub.d/40_custom)
#   TITLE_PREFIX  – menu entry label   (default: "Custom Linux")
#   KERNEL_ARGS   – extra kernel args  (default: "")
#
# Usage:
#   sudo bash scripts/add-all-initrd-grub.sh
#   sudo KERNEL_ARGS="quiet splash" bash scripts/add-all-initrd-grub.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration (override via environment)
# ---------------------------------------------------------------------------
BOOT_DIR="${BOOT_DIR:-/boot}"
GRUB_CUSTOM="${GRUB_CUSTOM:-/etc/grub.d/40_custom}"
TITLE_PREFIX="${TITLE_PREFIX:-Custom Linux}"
KERNEL_ARGS="${KERNEL_ARGS:-}"

readonly BEGIN_MARKER="### BEGIN AUTO-GENERATED INITRD ENTRIES"
readonly END_MARKER="### END AUTO-GENERATED INITRD ENTRIES"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
die()  { echo "ERROR: $*" >&2; exit 1; }
warn() { echo "WARN:  $*" >&2; }
info() { echo "INFO:  $*" >&2; }

check_root() {
    if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
        die "このスクリプトは root 権限が必要です。sudo で実行してください。"$'\n'"  例: sudo bash $0"
    fi
}

# Return the GRUB update command string, or empty string if not found.
detect_grub_update_cmd() {
    if command -v update-grub >/dev/null 2>&1; then
        echo "update-grub"
    elif command -v grub-mkconfig >/dev/null 2>&1; then
        local cfg
        if [[ -d /boot/grub2 ]]; then
            cfg="/boot/grub2/grub.cfg"
        else
            cfg="/boot/grub/grub.cfg"
        fi
        echo "grub-mkconfig -o ${cfg}"
    else
        echo ""
    fi
}

# Extract the version string from an initrd filename.
#   initrd.img-6.8.0-90-generic  ->  6.8.0-90-generic
extract_version() {
    local basename
    basename="$(basename "$1")"
    # Only handle initrd.img-<version> (with a non-empty version suffix)
    case "${basename}" in
        initrd.img-?*)
            echo "${basename#initrd.img-}"
            ;;
        *)
            echo ""
            ;;
    esac
}

# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------
build_grub_entries() {
    local entries_tmp
    entries_tmp="$(mktemp)"
    # shellcheck disable=SC2064
    trap "rm -f '${entries_tmp}'" RETURN

    {
        echo "${BEGIN_MARKER}"
        echo "# Generated by $0 on $(date -Iseconds)"
        echo "# Do not edit this block manually – it will be overwritten on next run."
        echo ""
    } >> "${entries_tmp}"

    local count=0

    # Sort results for deterministic ordering
    shopt -s nullglob
    local initrd_files
    # Read into array explicitly so nullglob works reliably
    initrd_files=( "${BOOT_DIR}"/initrd.img-* )
    shopt -u nullglob

    if [[ "${#initrd_files[@]}" -eq 0 ]]; then
        die "${BOOT_DIR} に initrd.img-<version> ファイルが見つかりませんでした。"
    fi

    for initrd in "${initrd_files[@]}"; do
        # Skip symlinks / alias files (initrd.img with no version suffix handled
        # by the glob, but guard against edge cases like "initrd.img-" with empty version)
        local version
        version="$(extract_version "${initrd}")"
        if [[ -z "${version}" ]]; then
            warn "バージョン番号が取得できないためスキップ: ${initrd}"
            continue
        fi

        local vmlinuz="${BOOT_DIR}/vmlinuz-${version}"
        if [[ ! -e "${vmlinuz}" ]]; then
            warn "対応する vmlinuz が見つからないためスキップ: ${vmlinuz}"
            continue
        fi

        local title="${TITLE_PREFIX} (kernel ${version})"
        # Build linux line; trim trailing whitespace when KERNEL_ARGS is empty
        local linux_args="${vmlinuz}"
        [[ -n "${KERNEL_ARGS}" ]] && linux_args="${linux_args} ${KERNEL_ARGS}"

        cat >> "${entries_tmp}" <<EOF
menuentry "${title}" {
    linux   ${linux_args}
    initrd  ${initrd}
}

EOF
        info "エントリを追加: ${title}"
        (( count++ )) || true
    done

    echo "${END_MARKER}" >> "${entries_tmp}"

    if [[ "${count}" -eq 0 ]]; then
        die "有効な起動エントリが生成されませんでした。vmlinuz-<version> ファイルを確認してください。"
    fi

    echo "${entries_tmp}"
    # Prevent RETURN trap from deleting the file before caller reads it
    trap - RETURN
}

write_to_grub_custom() {
    local entries_file="$1"

    # Ensure the file exists with the correct shebang expected by GRUB
    if [[ ! -f "${GRUB_CUSTOM}" ]]; then
        cat > "${GRUB_CUSTOM}" <<'HEADER'
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.
HEADER
        chmod +x "${GRUB_CUSTOM}"
        info "${GRUB_CUSTOM} を新規作成しました。"
    fi

    # Strip any previously generated block from the file
    local stripped_tmp
    stripped_tmp="$(mktemp)"
    awk "
        /^${BEGIN_MARKER}/{skip=1; next}
        /^${END_MARKER}/{skip=0; next}
        skip==0{print}
    " "${GRUB_CUSTOM}" > "${stripped_tmp}"

    # Append new entries
    cat "${entries_file}" >> "${stripped_tmp}"

    # Atomic replace
    cat "${stripped_tmp}" > "${GRUB_CUSTOM}"
    rm -f "${stripped_tmp}" "${entries_file}"

    info "${GRUB_CUSTOM} を更新しました。"
}

run_grub_update() {
    local cmd
    cmd="$(detect_grub_update_cmd)"
    if [[ -z "${cmd}" ]]; then
        warn "update-grub / grub-mkconfig が見つかりませんでした。手動で GRUB を更新してください。"
        return
    fi
    info "GRUB を更新中: ${cmd}"
    # Use read-array to safely split the command into words
    local -a cmd_array
    read -ra cmd_array <<< "${cmd}"
    "${cmd_array[@]}"
    info "GRUB の更新が完了しました。"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    check_root

    info "=== GRUB initrd エントリ自動生成スクリプト ==="
    info "スキャン対象: ${BOOT_DIR}/initrd.img-*"
    info "書き込み先:   ${GRUB_CUSTOM}"
    echo ""

    local entries_file
    entries_file="$(build_grub_entries)"
    write_to_grub_custom "${entries_file}"

    echo ""
    run_grub_update

    echo ""
    info "完了しました。"
}

main "$@"
